version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://school_user:school_pass@db:5432/school_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
